#
# Define OS
#
FROM alpine:3.14

#
# Basic OS management
#

# Install packages
RUN apk add --no-cache nodejs npm

#
# Require _defaults app
#

# # Create _defaults directory
# WORKDIR /_defaults

# # Bundle _defaults source
# COPY ./_defaults .

# Install dependencies
# RUN npm ci --only=production

#
# Require app
#

# Create app directory
WORKDIR /app

# Bundle app source
COPY ./cms .

# Install dependencies
RUN npm ci

#
# Setup app
#

# Expose app
EXPOSE 1337

# Set node env
ENV NODE_ENV=production

# Run app
CMD ["npm", "run", "develop"]